//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2ndviewer {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2ndviewer.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   moved near av(10m) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string chatLocAv {
            get {
                return ResourceManager.GetString("chatLocAv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://yutori.2ch.net/news4vip/subject.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultNews4VipUrl {
            get {
                return ResourceManager.GetString("defaultNews4VipUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tachikawa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultNickName {
            get {
                return ResourceManager.GetString("defaultNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   disconnected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   logout and exit application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed attach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedAttach {
            get {
                return ResourceManager.GetString("failedAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed detach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedDetach {
            get {
                return ResourceManager.GetString("failedDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedLogin {
            get {
                return ResourceManager.GetString("failedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed teleport に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedTeleport {
            get {
                return ResourceManager.GetString("failedTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///    is offline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string offlineMessage {
            get {
                return ResourceManager.GetString("offlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    is online に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string onlineMessage {
            get {
                return ResourceManager.GetString("onlineMessage", resourceCulture);
            }
        }
    }
}
